# Generated by Django 2.2.4 on 2019-09-04 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('exam_setter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_setter_set', to=settings.AUTH_USER_MODEL)),
                ('external_examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_reviewer_set', to=settings.AUTH_USER_MODEL)),
                ('internal_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_reviewer_set', to=settings.AUTH_USER_MODEL)),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observer_set', to=settings.AUTH_USER_MODEL)),
                ('school_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_office_set', to=settings.AUTH_USER_MODEL)),
                ('vetting_committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vetting_committee_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
