# Generated by Django 2.2.4 on 2019-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('EXAM_STAFF', 'Exam Staff'), ('EXTERNAL_EXAMINER', 'External Examiner'), ('SCHOOL_OFFICE', 'School Office')], default='', max_length=19),
        ),
    ]
