# Generated by Django 2.2.4 on 2019-09-04 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuidelineDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('document', models.FileField(upload_to='guideline_documents/docs/')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Module Code')),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionDeadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('academic_start_year', models.PositiveIntegerField(verbose_name='Academic Start Year')),
                ('initial_draft_submission', models.DateField()),
                ('internal_review_response', models.DateField()),
                ('internal_review_amendments', models.DateField()),
                ('vetting_committee_response', models.DateField()),
                ('vetting_committee_amendments', models.DateField()),
                ('external_review_response', models.DateField()),
                ('school_office_submission', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
